default_contract_address: ""

blockchains:
- name: polygon_amoy
  id: 80002
  contract_address: ""
- name: base_sepolia
  id: 84532
  contract_address: ""
- name: ethereum_sepolia
  id: 11155111
  disabled: true
  contract_address: ""
- name: linea_sepolia
  id: 59141
  disabled: true
  contract_address: ""
- name: xrpl_evm_testnet
  id: 1449000
  disabled: true
  contract_address: ""
  block_step: 499
