config:
  database:
    password: ref+tfstategs://terraform-state-deploy/gke-uat-postgresql-admin/default.tfstate/output.postgresql_user_passwords["clearnet_sandbox_admin"]
  secretEnvs:
    BROKER_PRIVATE_KEY: ref+gcpsecrets://ynet-stage/clearnet-sandbox-broker-private-key?version=latest
    POLYGON_AMOI_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-sandbox-polygon-amoi-infura-url?version=latest
    BASE_SEPOLIA_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-sandbox-base-sepolia-infura-url?version=latest
    ETH_SEPOLIA_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-sandbox-eth-sepolia-infura-url?version=latest
    LINEA_SEPOLIA_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-sandbox-linea-sepolia-infura-url?version=latest
