assets:
  - name: "USD Circle"
    symbol: "usdc"
    decimals: 6
    tokens:
      - blockchain_id: 11155111
        address: "0x6E2C4707DA119425dF2c722E2695300154652f56"
        decimals: 6
  - name: "Wrapped ETH"
    symbol: "weth"
    decimals: 18
    tokens:
      - blockchain_id: 11155111
        address: "0x2A35728CADd8076dfD424fC3e20974A3CD03bFa5"
        decimals: 18
