assets:
  - name: "USD Coin"
    symbol: "usdc"
    tokens:
      - blockchain_id: 1
        address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        decimals: 6
      - blockchain_id: 14
        symbol: "USDC.e"
        address: "0xFbDa5F676cB37624f28265A144A48B0d6e87d3b6"
        decimals: 6
      - blockchain_id: 137
        address: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
        decimals: 6
      - blockchain_id: 480
        address: "0x79A02482A880bCE3F13e09Da970dC34db4CD24d1"
        decimals: 6
      - blockchain_id: 30
        address: "0x3A15461d8AE0f0Fb5fA2629e9dA7D66A794a6E37"
        decimals: 18
      - blockchain_id: 747
        address: "0x2aaBea2058b5aC2D339b163C6Ab6f2b6d53aabED"
        decimals: 6
      - blockchain_id: 2020
        address: "0x0b7007c13325c48911f73a2dad5fa5dcbf808adc"
        decimals: 6
      - blockchain_id: 8453
        address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
        decimals: 6
      - blockchain_id: 59144
        address: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff"
        decimals: 6
      - blockchain_id: 1440000
        address: "0xa16148c6Ac9EDe0D82f0c52899e22a575284f131"
        decimals: 6
  - name: "Tether USD"
    symbol: "usdt"
    tokens:
      - blockchain_id: 8453
        address: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
        decimals: 6
      - blockchain_id: 59144
        address: "0xA219439258ca9da29E9Cc4cE5596924745e12B93"
        decimals: 6
  - name: "Ether"
    symbol: "eth"
    tokens:
      - blockchain_id: 8453
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
      - blockchain_id: 59144
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
  - name: "wETH"
    symbol: "weth"
    tokens:
      - blockchain_id: 137
        address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
        decimals: 18
  - symbol: "beatwav"
    tokens:
      - blockchain_id: 137
        address: "0x45268ba6c9A0459Eda6F6fAb4E5083c61730F375"
        decimals: 6
      - blockchain_id: 1
        address: "0xDB33fEC4e2994a675133320867a6439Da4A5acD8"
        decimals: 18
  - name: "Ripple"
    symbol: "xrp"
    tokens:
      - blockchain_id: 1440000
        address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
        decimals: 18
